### ISSUE TITLE
Error when using zoom in the browser

### ISSUE THREAD

**Issue by tuankiet234** [legalthings/angular-signature#16]
when i zoom in the browser (> 100%), then ctrl + 0 to back, i draw out of the region of the canvas

**Comment by tuankiet234** [comment]
![capture](https://cloud.githubusercontent.com/assets/9304314/15103833/792c50a0-15da-11e6-91bf-7370f79d33c0.PNG)

**Comment by jasny** [comment]
Probably same as #11
