### ISSUE TITLE
How to create multiple Instances of signature pad ?

### ISSUE THREAD

**Issue by khanstudio-github** [legalthings/angular-signature#30]
I am having a problem when I create two instances of signature pad. Only the late one is working properly but first one is not.  As you can see in the below image. Please can anyone help. Thank you

![error in first pad](https://cloud.githubusercontent.com/assets/20010783/18810269/e0f31d30-8246-11e6-93c7-8ba3714ae14d.png)

**Comment by mafeifan** [comment]
same question +1

**Comment by mafeifan** [comment]
in src/signature.js.  try  to just change '=?'  to '<?'

```
      scope: {
        accept: '<?',
        clear: '<?',
        dataurl: '<?',
        height: '@',
        width: '@',
        notifyDrawing: '&onDrawing',
      },
```

**Comment by jasny** [comment]
@khanstudio-github @mafeifan It should work out of the box. You shouldn't make the scope one way binding.

Could either of you please post the code (or create a [JSFiddle](http://jsfiddle.net)) you're using to please 2 signatures?

**Comment by pradeepranasinghe** [comment]
+1

**Comment by pradeepranasinghe** [comment]
when i do this:
   this.signaturePad2.fromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAM6ElEQVR4Xu2dW8g+VRXGH+.....');

Same value is set for both instances of the signature pad.

**Comment by mafeifan** [comment]
try http://plnkr.co/pwJNRmn5PhI53iVUOdpg

**Comment by pradeepranasinghe** [comment]
Thanks mafeifan! I will try this.

**Comment by mcblum** [comment]
I'm having the same issue. We have multiple signature pads in the dom but the panels they are in are hidden. For whatever reason, users keep having issues. Almost everyone can sign the first one but not the subsequent ones. Any idea what I could be doing wrong?

**Comment by jasny** [comment]
Again, this works out of the box. The only thing you should mind is saving the result in different objects. 

### See https://jsfiddle.net/91rdyehn/
