### ISSUE TITLE
Expression 'undefined' in attribute 'dataurl' used with directive 'signaturePad' is non-assignable

### ISSUE THREAD

**Issue by johhansantana** [legalthings/angular-signature#32]
I'm getting this weird console error sometimes whenever I write on the signature canvas.

The signature is working correctly and saving as it's suppose to but this pops up now and then.

```
<signature-pad accept="accept" clear="clear" ng-model="signature" height="220" width="568"></signature-pad>
          <button ng-click="clear()">Clear signature</button>
          <button ng-click="signature = accept(); checkSign(signature)">Sign</button>
```

**Comment by kevinsuzc** [comment]
add `dataurl=""` to the element of signature-pad

**Comment by jasny** [comment]
@kevinsuzc Thanks for you comment.
I'll leave this ticket open, because `dataurl` should be optional.

**Comment by jasny** [comment]
This is already reported #14
