### ISSUE TITLE
signature.dataUrl not set in 'accept'

### ISSUE THREAD

**Issue by d3vtoolsmith** [legalthings/angular-signature#37]
It seems like `.dataUrl` property is never set in the '`accept`' function anymore and so there's no way to get the url back (`dataurl`attribute also doesn't get it since it itself uses '`accept`' to get the signature).
Looks like the line was deleted as part of "Issue 34" commit.

**Comment by jasny** [comment]
The `dataurl` attribute is bound and doesn't react on 'accept'. Things are indeed broken. I've fixed them, but it today. See #36
