### ISSUE TITLE
how to draw image webURL into canvas.

### ISSUE THREAD

**Issue by rahulgupta20nov** [legalthings/angular-signature#45]
Hi,
I am getting base64 image data and uploading into a server, then server converts it into an image file and save in some location and return a web URL. After that, I want to edit the same signature then how I can draw the same image into the canvas.

**Comment by jasny** [comment]
You need to convert that image into a base64 string and than set the `dataurl`.

Please only use the issue tracker for bugs. If you need coding help, please use [stackoverflow](http://stackoverflow.com).
