### ISSUE TITLE
Reset image is not fit in canvas.

### ISSUE THREAD

**Issue by rahulgupta20nov** [legalthings/angular-signature#47]
When I click to sign button then clear image then click to reset button. 
So signature image is not come exact fit.

<img width="957" alt="screen shot 2016-12-13 at 2 43 10 pm" src="https://cloud.githubusercontent.com/assets/10140041/21134142/7fb83b5a-c142-11e6-887e-c1968443e984.png">

**Comment by Sarfaraaz** [comment]
What browser are you using?
Everything is confirmed to work fine in:
 * Google Chrome
 * Firefox
 * IE11
 * Edge

Patches are welcome.

**Comment by kfprimm** [comment]
I can confirm the above behavior. It seems to happen on high DPI devices. Using Chrome, my Android phone, iPad, & iMac all show the problem. However, an old 1080p Windows 7 machine works fine.

The [signature_pad README](https://github.com/szimek/signature_pad/#handling-high-dpi-screens) makes mention of this. I'm currently tinkering with the directive source & will report back if I make any progress.
