### ISSUE TITLE
Disable the directive

### ISSUE THREAD

**Issue by dashawk** [legalthings/angular-signature#50]
I cannot disable this, tried using `ng-disabled` but it did not work. However, there is an option from [here](https://github.com/szimek/signature_pad/) like this `signaturePad.off();`. I'm not sure where to put it.

**Comment by JonSnaka** [comment]
Hi,

I also needed this functionality, so I have made a PR for it. I added a disabled attribute to the directive for you to use. You can then use it like:  <signature-pad accept="accept" clear="clear" _**disabled="yourVariable"**_ height="200" width="700"></signature-pad>

Hope it helps!
