### ISSUE TITLE
Cannot draw in the canvas

### ISSUE THREAD

**Issue by armandomusto** [legalthings/angular-signature#56]
HI,
I am using signaturePad with Angular 1.3.17, and I am not able to draw anything in the pad.
I am debbuging signature.js and I think the mouseDown event is not working, even if mousup is working fine.
<div class="form-group">
<label for="name">Sign here</label>
<signature-pad  accept="accept" clear="clear" height="100" width="250" style="border: 1px solid orange;cursor:pointer;"></signature-pad>
</div>

It seems something in signature.js is not working as expected

I am running it into a modal.

**Comment by jasny** [comment]
@armandomusto Please try the demo to see if it works on your system.

If it's something specific about your app, please recreate it in a jsfiddle isolating the issue.

**Comment by jasny** [comment]
No response from OP
