### ISSUE TITLE
support multiple units of measurement for width/height #7

### ISSUE THREAD

**Issue by donalmurtagh** [legalthings/angular-signature#57]
Currently it seems that only pixel widths/heights are allowed in the form definition, e.g.
```
width: 100,
height: 100
```
To support responsive layouts, it would be helpful if other units are supported, e.g.
```
width: '50%',
height: '50%'
```

**Comment by jasny** [comment]
The size you specify is the size that the output image is going to be. Percentages doesn't make sense here.

The signature pad will scale down to fit the available width. So if you set the size to something `1024x1024` and set add `width: 50%` to the style of the containing div, the pad will have a width of 50% of the screen. The output image will be 1024 by 1024 pixels.

Check out the demo, which showcases this.

**Comment by donalmurtagh** [comment]
> Check out the demo, which showcases this.

I don't think the demo does showcase this, because no matter what size you choose for the signature pad, the size of the area you sign in (the box with the brown border) is always the same as the size of the generated signature image (the box with the blue border).

Changing the size of the signature pad only seems to affect the width of the element (with the red border) that _contains_ the signature pad. 

![screen shot](https://cloud.githubusercontent.com/assets/11269693/26308231/3c728af4-3ef0-11e7-8f1c-df07ed744242.png)

**Comment by jasny** [comment]
@donalmurtagh The pad will only shrink, never grow. You need to increase the width and height attributes.
