### ISSUE TITLE
dataUrl is undefined and isEmpty function returns true even if valid signature is provided

### ISSUE THREAD

**Issue by elsatom** [legalthings/angular-signature#59]
Tested both in Chrome and Firefox. This issue is intermittent

**Comment by jasny** [comment]
@elsatom We've not seen this issue. We need to be able to reproduce an issue in order to solve it.

Please try to find a reproducible case and add a JSFiddle.

**Comment by c5racing** [comment]
This issue appear to occur whenever a user goes outside of the signature bounds.  Even though the signature is there, the dataUrl is empty.

This is related to Issue #44

**Comment by jasny** [comment]
Closing as duplicate
