### ISSUE TITLE
signaturePad undefined. Why is this coming back undefined.

### ISSUE THREAD

**Issue by Go4th** [legalthings/angular-signature#60]
I'm getting this error in my console. 
SignaturePad is not defined
    at link (http://localhost:8100/lib/signature.js:81:34)

When I click into the signature.js to this line:character, 
 scope.signaturePad = new SignaturePad(canvas);

How can I fix this?

**Comment by jasny** [comment]
You need to load the [signaturepad js library](https://github.com/szimek/signature_pad). This plugin depends on it.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/signature_pad/1.5.3/signature_pad.min.js"></script>
```
