### ISSUE TITLE
Doesn't allow for more than one signature pad

### ISSUE THREAD

**Issue by austinsk8s** [legalthings/angular-signature#7]
From what I can tell. You can only have one signature spot on a page. If two people must sign a document, the accept and clear buttons will only reference the second signature pad, even if the accept="" and clear="" attributes for the different pads reference different buttons. 

```
<signature-pad accept="accept1" clear="clear1"></signature-pad>
<button ng-click="clear1()">Clear signature</button>
<button ng-click="signature1 = accept1()">Sign</button>

<signature-pad accept="accept2" clear="clear2"></signature-pad>
<button ng-click="clear2()">Clear signature</button>
<button ng-click="signature2 = accept2()">Sign</button>
```

Even though they have different buttons, hitting the clear button for either signature pad will clear the second pad. The first pad is rendered useless if a second pad exists.

**Comment by austinsk8s** [comment]
Thanks for the fix! I hacked in my own array based solution. It makes so much more sense and is much cleaner just to use $scope. I don't know why I didn't think of that.

**Comment by snobrdinrtiste** [comment]
can someone share an example to how to achieve having two signature pads on the same page?
